### ISSUE TITLE
Merge markdown2clj and mdmorph ?

### ISSUE THREAD

**Issue by dgellow** [nilenso/markdown2clj#4]
Hello,

I created a project called [mdmorph](https://github.com/dgellow/mdmorph) to export an AST generated by markdown2clj into something else (HTML, etc).
Would you be interested by a pull request to merge it into markdown2clj?

Right now it doesn't cover everything, just what I needed but we can make a more complete version.

**Comment by ukriish** [comment]
Hi @dgellow,

Let me apologize for the delayed response, glad to know you are using `markdown2clj` :smile:. Also let me add, `mdmorph` looks pretty good.

One of the reason this library exists is because we extracted it out from our [markdown2docx](https://github.com/nilenso/markdown2docx) utility, so that `markdown2clj` could be used as an standalone library that did just one thing : convert a markdown string to a clojure data-structure(_hashmap_). While we like the idea of extending `markdown2clj` to output various formats, we feel that it would be better if it lived in its own namespace.

At the same time, we could purse something in the path of creating a `markdown2x` repository that houses these libraries/utilities. Let me know what you think.

-- krish

**Comment by dgellow** [comment]
Yeah, 👍 for a `markdown2x` project!

What exactly do you have in mind?
I like the idea of a protocol as it allows users to implement their own renderer. But I'm not sure how to design it to support something as complicated as docx can be (I don't say that we should reimplement `markdown2docx` with it, it's just an example of a complex format, with tables, footnotes, table of content and surely other things). 

Maybe it can be done with multiple protocols, like a basic `Renderable`, a `Footer`, a `Header`, etc?

``` clj
(defrecord HTMLRenderer []
  Renderable
  (heading [this opts] ...)
  (paragraph [this opts] ...)

  Header
  (header [this opts] ...)

  Footer
  (footer [this opts] ...))
```

Btw I didn't put a lot of thoughts into it, just something I have in mind right now. But anyway, I'm happy to see that you're open to a project like `markdown2x` :)
Do you prefer to keep the project in [nilenso](https://github.com/nilenso) or somewhere else?
